version: '3.7'

services:

  oncare:
    container_name: oncare
    build:
      context: .
      dockerfile: Dockerfile
    image: doc_container_2

    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 8000:8000
    environment:
      - CHOKIDAR_USEPOLLING=true